# Generated by Django 5.2.3 on 2025-06-27 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='reviewer',
            field=models.CharField(default='ainas'),
            preserve_default=False,
        ),
    ]
